from CommonConst.GlobalConstant import *

__all__ = ['CLOSE_BUTTON_IMG',
           'TALENT_CURRENT_ELF',
           'CONFIRM_CHANGE_CURRENT_ELF_TALENT',
           'ELF_GRID_IN_BAG',
           'TALENT_TITLE_IMG',
           'TIP_ORDINARY_REMODELING',
           'TIP_HIGH_LEVEL_REMODELING',
           'ORIGINAL_TALENT_CHANGE_COST',
           'HIGH_LEVEL_TALENT_CHANGE_COST',
           'TIP_VIP_WELFARE',
           'ELF_ATTRIBUTES',
           'ELF_STARS_COLORS',
           'COMMON_TIP_QSS',
           'ELF_TYPES',
           'TALENT_STAR_DISTANCE_SHOW',
           'ELF_SKILLS',
           'MAX_SINGLE_TALENT_ATTR_VALUE',
           'MIN_SINGLE_TALENT_ATTR_VALUE',
           'PETS_CODEX',
           'STAR_STYLES',
           'GAME_ICO',
           'TEST_USER_INFO',
           'CURRENT_TASK_STATUS'
           ]
